name: VisuWarpSpigot
version: '${version}'
main: hoosk.visuwarpspigot.VisuWarpSpigot
api-version: '1.20'
author: Juskie
description: A simple plugin which assigns warps to a visual menu.

classes:
  - hoosk.visuwarpspigot.util.Warp

commands:
  addwarp:
    description: Used to add warp to global warps menu
    usage: /addwarp (warpname) {description}
    permission: op
    permission-message: Sorry, you don't have permission to use this command.
  vwmenu:
    description: Opens the warp menu
    usage: |
      /<command> open - Open the warp menu
      /<command> list - List all warps
      /<command> add <warpname> <description> - Adds a warp
      /<command> remove <warpname> - Remove a warp
      /<command> version - Display plugin version
    aliases: [vwmenu]
    permission-message: Sorry, you don't have permission to use this command.

permissions:
  visuwarp.*:
    description: gives full access to visuwarp commands
    children:
      visuwarp.open: true
      visuwarp.list: true
      visuwarp.add: true
      visuwarp.remove: true
      visuwarp.version: true